"""
core/state.py

Central Pydantic models for the CloudDash Agent Gateway.
All data flowing between agents MUST be typed via these models.
No raw dicts are permitted across agent/node boundaries.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Annotated, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class AgentRole(str, Enum):
    """Identifies which specialist agent owns the current turn."""

    TRIAGE = "triage"
    TECH_SUPPORT = "tech_support"
    BILLING = "billing"
    ESCALATION = "escalation"


class MessageRole(str, Enum):
    """Speaker role within a conversation turn."""

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"
    TOOL = "tool"


class ConversationStatus(str, Enum):
    """Lifecycle status of a conversation session."""

    ACTIVE = "active"
    PENDING_ESCALATION = "pending_escalation"
    RESOLVED = "resolved"
    CLOSED = "closed"


# ---------------------------------------------------------------------------
# Message
# ---------------------------------------------------------------------------


class Message(BaseModel):
    """
    Represents a single turn in the conversation history.

    Attributes:
        id:         Unique message identifier (auto-generated UUID4).
        role:       Speaker role — user, assistant, system, or tool.
        content:    Raw text content of the message.
        agent:      Which agent produced this message (None for user/system).
        timestamp:  UTC creation time (auto-set on instantiation).
        metadata:   Optional key-value bag for tracing, token counts, etc.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    role: MessageRole
    content: str = Field(..., min_length=1)
    agent: Optional[AgentRole] = None
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    metadata: dict[str, str] = Field(default_factory=dict)

    @field_validator("content")
    @classmethod
    def content_must_not_be_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Message content must not be blank or whitespace-only.")
        return v

    model_config = {"frozen": True}  # Messages are immutable once created.


# ---------------------------------------------------------------------------
# HandoverPayload
# ---------------------------------------------------------------------------


class HandoverPayload(BaseModel):
    """
    Typed contract passed from the Triage supervisor to a specialist agent.

    The Triage agent MUST populate this before routing; specialist agents
    read it to understand context without re-reading the full history.

    Attributes:
        trace_id:          Propagated request trace ID for end-to-end logging.
        from_agent:        Agent initiating the handover (always Triage on
                           first routing; can be a specialist on re-routing).
        to_agent:          Target specialist that should handle next turn.
        intent:            Short intent label surfaced by the classifier
                           (e.g. "billing_dispute", "connectivity_issue").
        confidence:        Classifier confidence score [0.0, 1.0].
        summary:           One-sentence summary of the conversation so far,
                           generated by the Triage agent to save specialist
                           context tokens.
        rag_required:      Hint to the specialist — should it run RAG retrieval?
        escalation_reason: Populated only when routing to the Escalation agent.
    """

    trace_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    from_agent: AgentRole
    to_agent: AgentRole
    intent: str = Field(..., min_length=1, max_length=128)
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    summary: str = Field(..., min_length=1, max_length=1024)
    rag_required: bool = False
    escalation_reason: Optional[str] = Field(default=None, max_length=512)

    @field_validator("to_agent")
    @classmethod
    def triage_cannot_be_destination(cls, v: AgentRole) -> AgentRole:
        if v == AgentRole.TRIAGE:
            raise ValueError(
                "HandoverPayload.to_agent cannot be TRIAGE. "
                "Triage is a supervisor, not a specialist destination."
            )
        return v

    @field_validator("escalation_reason")
    @classmethod
    def escalation_reason_required_when_escalating(
        cls, v: Optional[str], info  # `info` gives access to other field values
    ) -> Optional[str]:
        # Access sibling field via model_fields_set / values dict
        to_agent = info.data.get("to_agent")
        if to_agent == AgentRole.ESCALATION and not v:
            raise ValueError(
                "escalation_reason must be provided when routing to ESCALATION."
            )
        return v


# ---------------------------------------------------------------------------
# ConversationState
# ---------------------------------------------------------------------------


class ConversationState(BaseModel):
    """
    The canonical shared state object that flows through the LangGraph graph.

    This is the *single source of truth* for a conversation session.
    Every LangGraph node receives and returns a (potentially updated) copy
    of this model — never a raw dict.

    Attributes:
        session_id:      Unique identifier for this conversation session.
        trace_id:        Active request trace ID (refreshed per API call).
        status:          Lifecycle status of the conversation.
        current_agent:   Which agent is currently handling the conversation.
        history:         Ordered list of all messages in this session.
        handover:        Most recent HandoverPayload (None if no routing yet).
        rag_citations:   Source document references injected by RAG retrieval.
        user_id:         Opaque external user identifier (for Supabase lookups).
        customer_tier:   Customer plan tier; used by Billing agent for context.
        turn_count:      Total number of user turns in the session.
        created_at:      UTC timestamp when the session was created.
        updated_at:      UTC timestamp of the last state mutation.
        error:           Last error message, if any node faulted gracefully.
    """

    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    trace_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    status: ConversationStatus = ConversationStatus.ACTIVE
    current_agent: AgentRole = AgentRole.TRIAGE
    history: List[Message] = Field(default_factory=list)
    handover: Optional[HandoverPayload] = None          # Latest handover (convenience shortcut)
    handover_history: List[HandoverPayload] = Field(default_factory=list)  # Full routing audit trail
    rag_citations: List[str] = Field(default_factory=list)
    user_id: Optional[str] = None
    customer_tier: Optional[Literal["free", "pro", "enterprise"]] = None
    turn_count: int = Field(default=0, ge=0)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    error: Optional[str] = None

    # ------------------------------------------------------------------
    # Convenience helpers (pure — do not mutate self)
    # ------------------------------------------------------------------

    def with_message(self, message: Message) -> "ConversationState":
        """Return a new state with `message` appended to history."""
        return self.model_copy(
            update={
                "history": [*self.history, message],
                "turn_count": self.turn_count + (1 if message.role == MessageRole.USER else 0),
                "updated_at": datetime.now(timezone.utc),
            }
        )

    def with_handover(self, payload: HandoverPayload) -> "ConversationState":
        """Return a new state reflecting an agent routing decision.

        Both `handover` (latest shortcut) and `handover_history` (full audit
        trail) are updated atomically so consumers can use whichever is convenient.
        """
        return self.model_copy(
            update={
                "handover": payload,
                "handover_history": [*self.handover_history, payload],
                "current_agent": payload.to_agent,
                "updated_at": datetime.now(timezone.utc),
            }
        )

    def with_error(self, error_msg: str) -> "ConversationState":
        """Return a new state with an error annotation (non-fatal path)."""
        return self.model_copy(
            update={
                "error": error_msg,
                "updated_at": datetime.now(timezone.utc),
            }
        )

    def latest_user_message(self) -> Optional[Message]:
        """Return the most recent user-role message, or None."""
        for msg in reversed(self.history):
            if msg.role == MessageRole.USER:
                return msg
        return None
